name: DankTech2
author: Sefiraat
description: 黏液科技附加 丹克科技2 繁體翻譯版.
main: io.github.sefiraat.danktech2.DankTech2
website: https://github.com/Sefiraat/DankTech2
version: ${project.version}
api-version: 1.16
depend:
  - Slimefun
softdepend:
  - mcMMO
  - RoseStacker
  - WildStacker
commands:
  danktech2:
    description: /danktech2
    usage: /danktech2 <sub>
    aliases: [ dt, dank ]